spring:
  application:
    name: tilias-web-management

  datasource:
#    url: jdbc:mysql://192.168.100.128:3306/tlias
#    在docker内部直接使用容器名
    url: jdbc:mysql://mysql:3306/tlias
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

#日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: zcf-javaweb-learning
    region: cn-beijing



